apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: ldap-service.ldap.svc.cluster.local:636
        insecureNoSSL: false
        insecureSkipVerify: false
        rootCA: /etc/dex/tls/ca.crt
        bindDN: cn=admin,dc=tilyes,dc=eu
        bindPW: $LDAP_ADMIN_PASSWORD
        usernamePrompt: username
        userSearch:
          baseDN: ou=People,dc=tilyes,dc=eu
          filter: "(objectClass=inetOrgPerson)"
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: givenName
        groupSearch:
          baseDN: ou=Groups,dc=tilyes,dc=eu
          filter: "(objectClass=groupOfNames)"
          userAttr: DN
          groupAttr: member
          nameAttr: cn
